// <auto-generated />
using System;
using AspCoreServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp2017.Migrations
{
    [DbContext(typeof(SpaDbContext))]
    partial class SpaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Asp2017.Server.Models.Estimate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("ProjectName");

                    b.HasKey("ID");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
